Repository CausticCove/Caustic-Cove-Main, pull requests merged in 2024-12, with the labels that each got.

#83 Reduce/Grow Spell, Whip Rebalance, Summon Fix, etc
  code/datums/components/pact_weapon.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/modules/client/customizer/customizers/organ/snout.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/mob/dead/new_player/sprite_accessory/snouts.dm
  code/modules/spells/roguetown/warlock.dm
  icons/mob/actions/roguespells.dmi
  icons/mob/sprite_accessory/snouts/snouts.dmi
  modular_causticcove/code/modules/spells/wizard.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  roguetown.dme
Labels: Spriting

#93 Nau food fix and additions, Rogue's Fixing and Balance,
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/cooked/NeuFood_meals.dm
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular/Neu_Food/code/raw/NeuFood_veggies.dm
  modular/Neu_Food/icons/food.dmi
Labels: Balance

#104 Artificers and Gun Updates
  code/game/objects/items/rogueweapons/ranged/gunpowder/runelock.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  modular_causticcove/code/modules/roguetown/roguejobs/Engineer/anvil_recipes/mechanical.dm
  roguetown.dme
Labels: Balance

#103 Adds the Covus Cruiser Map (Testmerge)
  _maps/covuscruiser.dm
  _maps/covuscruiser.json
  _maps/map_files/covuscruiser/covuscruiser.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/game/objects/structures/tables_racks.dm
  config/config.txt
  config/maps.txt
  sound/music/area/middeckdrone.ogg
  sound/music/area/nobledeckdrone.ogg
  sound/music/area/shipbrig.ogg
  sound/music/area/topdeckdrone.ogg
Labels: Mapping

#97 Changes, QoL, Classes additions
  code/game/objects/items/rogueitems/natural.dm
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/cargo/packsrogue/Sellsword.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/npc/goblin.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/musketeer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/mob/dead/new_player/sprite_accessory/genitals.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/mob/sprite_accessory/genitals/butt.dmi
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/cooked/NeuFood_meals.dm
  roguetown.dme
Labels: Balance, Spriting

#107 Test Merge - Quiver fix
  _maps/custom/roguetown2.dmm
  _maps/map_files/backup2/roguetown.dmm
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/grimoria/roguetown.dmm
  _maps/map_files/grimoria/roguetown2.dmm
  _maps/map_files/oldtown/oldtown.dmm
  _maps/map_files/otherz/bog.dmm
  _maps/map_files/otherz/smallforest.dmm
  _maps/map_files/rockhill/rockhill.dmm
  _maps/map_files/roguetest/roguetest.dmm
  _maps/map_files/roguetown/old/roguetown.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/roguetown2/roguetown2.dmm
  _maps/templates/smalldungeons.dm
  code/datums/special_traits/traits/traits.dm
  code/modules/cargo/packsrogue/Knave.dm
  code/modules/cargo/packsrogue/Sellsword.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/clothing/rogueclothes/quiver.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/dwarfranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/musketeer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/garrison/gatemaster.dm
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/boltslinger.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguemachine/drugmachine.dm
  code/modules/roguetown/roguestock/import.dm
Labels: Mapping, Balance
