Repository CausticCove/Caustic-Cove-Main, pull requests merged in 2024-10, with the labels that each got.

#31 Estoc and Rapier updates
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/weapons/64.dmi
Labels: Balance, Spriting

#34 Fixes celestial/infernal font, tiefling tail wags
  code/__DEFINES/say.dm
  code/modules/client/customizer/customizers/organ/horns.dm
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/mob/dead/new_player/sprite_accessory/horns.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  code/modules/surgery/organs/feature_organs/horns.dm
  icons/mob/sprite_accessory/horns/horns.dmi
  icons/mob/sprite_accessory/tails/tiefling.dmi
  icons/mob/sprite_accessory/tiefling.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_shirts.dmi
  interface/fonts/languages/hell.ttf
  interface/stylesheet.dm
Labels: Spriting

#35 Metal bucket craftable and chef knife fix
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  icons/roguetown/weapons/32.dmi
Labels: Spriting

#40 New Lux Sprite
  icons/roguetown/items/produce.dmi
Labels: Spriting

#42 Sewer Loot Rebalance + Flora Pit
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#43 Coastal Town District + Megaflora Pit
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/water.dm
  modular_causticcove/code/game/area/areas.dm
  modular_causticcove/sound/misc/bigmelt.ogg
  modular_causticcove/sound/misc/deathdigest.ogg
  modular_causticcove/sound/music/area/covuscarnipii.ogg
  roguetown.dme
Labels: Mapping

#47 Macro bugfix
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
Labels: Balance

#51 Map wide changes (flora plant, various dun manor changes)
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  roguetown.dme
Labels: Mapping

#52 Taur Bullshit
  code/__DEFINES/mobs.dm
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromacro.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/furry/demimacro.dm
  icons/mob/sprite_accessory/tails/fatnaga.dmi
  icons/mob/sprite_accessory/tails/feline.dmi
  icons/mob/sprite_accessory/tails/naga.dmi
  icons/mob/sprite_accessory/tails/sectdrone.dmi
  icons/mob/sprite_accessory/tails/spider.dmi
  icons/mob/sprite_accessory/tails/wolf.dmi
Labels: Spriting

#54 Taur fixes
  code/__DEFINES/mobs.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromacro.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/furry/demimacro.dm
Labels: Spriting

#56 Fixes!
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
Labels: Balance
