Repository CausticCove/Caustic-Cove-Main, pull requests merged in 2024-11, with the labels that each got.

#58 more fixes and markings
  code/modules/client/customizer/customizers/organ/tail_feature.dm
  code/modules/mob/dead/new_player/sprite_accessory/tail_features.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/furry/demimacro.dm
  icons/mob/sprite_accessory/tail_features/fat_sect_markings.dmi
  icons/mob/sprite_accessory/tail_features/fatnaga_markings.dmi
  icons/mob/sprite_accessory/tail_features/feline_markings.dmi
  icons/mob/sprite_accessory/tail_features/naga_markings.dmi
  icons/mob/sprite_accessory/tail_features/sect_markings.dmi
  icons/mob/sprite_accessory/tail_features/wolf_markings.dmi
  icons/mob/sprite_accessory/tails/fat_sect.dmi
Labels: Spriting

#60 more fixes and HOPEFULLY SQUARE SQUASHING
  code/modules/jobs/job_types/roguetown/roguetown.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromacro.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/furry/demimacro.dm
Labels: Balance

#62 Places Excidium
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#70 Readds Butcher Key to Butcher
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
Labels: Balance

#68 Lynx's Potions + Blood Volume regen tweaks
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/game/area/roguetownareas.dm
  code/game/objects/items/rogueitems/gems.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/water.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  code/modules/roguetown/roguejobs/cook/tools/grinding.dm
  code/modules/roguetown/roguemachine/vendor.dm
  icons/mob/screen_alert.dmi
  icons/roguetown/items/gems.dmi
  icons/roguetown/items/natural.dmi
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/cooked/NeuFood_meals.dm
  modular/Neu_Food/code/cooked/NeuFood_pies.dm
  modular/Neu_Food/code/cooked/NeuFood_snacks.dm
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular/Neu_Food/code/raw/NeuFood_processed.dm
  modular_azurepeak/code/modules/spells/orison.dm
  modular_azurepeak/icons/mob/flaming_hands.dmi
  modular_causticcove/code/__DEFINES/status_effects.dm
  modular_causticcove/code/datums/status_effects/rogue/causticbuff.dm
  modular_causticcove/code/game/area/objects/items/rogueitems/natural/animals.dm
  modular_causticcove/code/modules/roguetown/roguecrafting/alchemy.dm
  modular_causticcove/code/modules/roguetown/roguejobs/alchemist/containers.dm
  modular_causticcove/code/modules/roguetown/roguejobs/alchemist/reagent.dm
  roguetown.dme
Labels: Balance, Spriting

#77 EVIL UPDATE
  code/datums/skills/combat.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/ammo.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/arquebus.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/handgonne.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/items.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/pistol.dm
  code/game/objects/items/rogueweapons/ranged/gunpowder/runelock.dm
  code/modules/clothing/rogueclothes/quiver.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/mob/dead/new_player/sprite_accessory/tail_features.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm
  code/modules/surgery/organs/eyes.dm
  icons/mob/sprite_accessory/tail_features/dragon_tail_marking.dmi
  icons/mob/sprite_accessory/tails/chomp big tails.dmi
  icons/mob/sprite_accessory/tails/cownose.dmi
  icons/mob/sprite_accessory/tails/dragon_tail.dmi
  icons/mob/sprite_accessory/tails/dragon_tail_marking.dmi
  icons/mob/sprite_accessory/tails/large dragon.dmi
  icons/mob/sprite_accessory/tails/orca.dmi
  icons/mob/sprite_accessory/tails/taurs_ch.dmi
  icons/obj/items/arquebus_items.dmi
  icons/obj/items/pouch.dmi
  icons/roguetown/weapons/ammo.dmi
  icons/roguetown/weapons/arquebus.dmi
  icons/roguetown/weapons/handgonne.dmi
  roguetown.dme
  sound/arquebus/arquefire.ogg
  sound/arquebus/arquefire2.ogg
  sound/arquebus/arquefire3.ogg
  sound/arquebus/arquefire4.ogg
  sound/arquebus/arquefire5.ogg
  sound/arquebus/fuse.ogg
  sound/arquebus/insert.ogg
  sound/arquebus/pour_powder.ogg
  sound/arquebus/ramrod.ogg
  sound/combat/Ranged/musketfire2.ogg
  sound/music/Grin.ogg
Labels: Balance, Spriting

#80 Additions and fixes
  code/_onclick/hud/screen_objects.dm
  code/datums/character_flaw/_character_flaw.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
  code/modules/mob/dead/new_player/sprite_accessory/_sprite_accessory.dm
  code/modules/mob/dead/new_player/sprite_accessory/genitals.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromacro.dm
  code/modules/mob/living/carbon/human/species_types/furry/demimacro.dm
  icons/roguetown/weapons/64.dmi
Labels: Balance, Spriting

#82 Adds loincloth as underwear option with mechanical impact
  code/game/objects/items/rogueitems/undies.dm
  code/modules/client/customizer/customizers/bodypart_feature/misc.dm
  code/modules/mob/dead/new_player/sprite_accessory/underwear.dm
  code/modules/mob/living/carbon/human/examine.dm
  icons/mob/sprite_accessory/underwear.dmi
  icons/roguetown/items/misc.dmi
Labels: Spriting

#85 Hoardmaster Icon Fix
  icons/roguetown/misc/96x96.dmi
Labels: Spriting

#87 Templar Weapon Fix
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Balance

#89 Templar Fix 2
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Balance

#92 Fix the PP!
  code/__DEFINES/DNA.dm
  code/__DEFINES/misc.dm
  code/datums/mob_descriptors/descriptors/other.dm
  code/modules/client/customizer/customizers/organ/genitals.dm
  code/modules/mob/dead/new_player/sprite_accessory/_sprite_accessory.dm
  code/modules/mob/dead/new_player/sprite_accessory/genitals.dm
  code/modules/mob/dead/new_player/sprite_accessory/tail_features.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/organs/feature_organs/genitals.dm
  icons/mob/sprite_accessory/genitals/breasts.dmi
  icons/mob/sprite_accessory/genitals/butt.dmi
  icons/mob/sprite_accessory/genitals/penis.dmi
  icons/mob/sprite_accessory/genitals/testicles.dmi
  icons/mob/sprite_accessory/genitals/vagina.dmi
Labels: Spriting
