Repository CausticCove/Caustic-Cove-Main, pull requests merged in 2024-09, with the labels that each got.

#1 Culls Azure Peak and Replaces With Caustic Cove
  _maps/map_files/dun_manor/azure_forest.dmm
  code/__HELPERS/names.dm
  code/__HELPERS/roundend.dm
  code/datums/gods/faiths/divine_pantheon.dm
  code/datums/migrants/migrant_wave.dm
  code/datums/migrants/migrant_waves/fablefield wave.dm
  code/game/area/roguetownareas.dm
  code/game/gamemodes/objectives_rogue.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetown/telescope.dm
  code/game/objects/structures/walldeco.dm
  code/modules/client/roundendmanifest.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/yeomen/alchemist.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
  code/modules/paperwork/rogue.dm
  code/modules/roguetown/roguejobs/fisher/fish.dm
  code/modules/roguetown/roguemachine/ATM.dm
  code/modules/roguetown/roguemachine/steward.dm
  code/modules/roguetown/roguemachine/throne.dm
  code/world.dm
  modular_azurepeak/code/game/objects/structures/fartravel.dm
Labels: Mapping, Balance

#4 Adventurer Slots Tweak
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/dbomb.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/dwarfranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/monk.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/necromancer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Balance

#6 Ratwood Prosthetics
  code/datums/character_flaw/limbloss.dm
  code/game/objects/items/rogueitems/prosthetics.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/mob/living/grabbing.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  icons/mob/species/anthro_small_female.dmi
  icons/mob/species/anthro_small_male.dmi
  icons/mob/species/female.dmi
  icons/mob/species/goblin_female.dmi
  icons/mob/species/goblin_male.dmi
  icons/mob/species/male.dmi
  icons/mob/species/moth_f.dmi
  icons/mob/species/moth_m.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/mob/bodies/f/fd.dmi
  icons/roguetown/mob/bodies/f/fm.dmi
  icons/roguetown/mob/bodies/f/ft_muscular.dmi
  icons/roguetown/mob/bodies/m/md.dmi
  icons/roguetown/mob/bodies/m/mem.dmi
  icons/roguetown/mob/bodies/m/met.dmi
  icons/roguetown/mob/bodies/m/mt.dmi
  icons/roguetown/mob/bodies/m/mt_muscular.dmi
  roguetown.dme
Labels: Spriting

#7 Multiple fixes
  code/game/objects/items/rogueitems/keys.dm
  code/modules/cargo/packsrogue/armor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
Labels: Balance

#8 Farming, Mining, and Hunting Tweaks
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/bait.dm
  code/modules/farming/composter.dm
  code/modules/farming/soil.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
  code/modules/roguetown/roguecrafting/farming.dm
  icons/roguetown/items/misc.dmi
  roguetown.dme
Labels: Mapping, Balance, Spriting

#10 Removes Kobold Racism
  _maps/map_files/dun_manor/dun_manor.dmm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
  code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
Labels: Mapping

#9 Fixes An Iffy Furnace In Farm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#12 Adds a Slot to Monarch
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
Labels: Balance

#13 More Minable Turfs
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#14 Ratwood Reagents
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/items/rogueitems/natural/ash.dm
  code/game/objects/items/rogueitems/natural/stones.dm
  code/game/objects/items/thermometer.dm
  code/game/turfs/closed/minerals.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/power/roguelighting.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/cat2_medicines.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/forge.dm
  code/modules/roguetown/roguejobs/cook/tools/pot.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/mob/screen_alert.dmi
  icons/obj/chemical.dmi
  icons/roguetown/items/ore.dmi
  roguetown.dme
Labels: Balance, Spriting

#15 Towner home claims
  _maps/map_files/dun_manor/dun_manor.dmm
  code/controllers/subsystem/rogue/role_class_handler/class_register.dm
  code/controllers/subsystem/rogue/role_class_handler/class_select_handler/class_select_handler.dm
  code/controllers/subsystem/rogue/role_class_handler/role_class_handler.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  roguetown.dme
Labels: Mapping

#18 Superior Kettle Helms
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
Labels: Spriting

#22 Initial Matchlock port
  code/game/objects/items/rogueweapons/ranged/matchlock.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/ammo.dmi
  roguetown.dme
  sound/combat/Ranged/musketfire.ogg
  sound/foley/musketcock.ogg
  sound/foley/musketload.ogg
Labels: Spriting

#25 Forest Smoothing
  code/game/turfs/open/floor/roguefloor.dm
  icons/turf/roguefloor.dmi
Labels: Spriting

#29 Big Azure Update
  code/game/objects/items/rogueitems/needle.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/tools.dm
  code/modules/roguetown/roguemachine/_withdraw_tab.dm
  code/modules/roguetown/roguemachine/scomm.dm
  code/modules/roguetown/roguemachine/steward.dm
  code/modules/roguetown/roguemachine/withdraw.dm
  code/modules/spells/spell.dm
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/cooked/NeuFood_meals.dm
Labels: Balance, Spriting
